### ISSUE TITLE
앱서버 개발 TODO

### ISSUE THREAD

**Issue by lancifollia** [sicamp17-boramsangjo/server#1]
TODO
- [x] 회원 가입/업데이트/탈퇴
  - [x] [app/createUser](https://github.com/sicamp17-boramsangjo/server/blob/develop/README.md#appcreateuser)
  - [x] [app/checkAlreadyJoin](https://github.com/sicamp17-boramsangjo/server/blob/develop/README.md#checkAlreadyJoin)
  - [x] [app/login](https://github.com/sicamp17-boramsangjo/server/blob/develop/README.md#applogin)
  - [x] [app/logout](https://github.com/sicamp17-boramsangjo/server/blob/develop/README.md#applogout)
  - [x] [app/deleteUser](https://github.com/sicamp17-boramsangjo/server/blob/develop/README.md#appdeleteuser)
  - [x] [app/updateUserInfo](https://github.com/sicamp17-boramsangjo/server/blob/develop/README.md#appupdateuserinfo)
  - [x] [app/getUserInfo](https://github.com/sicamp17-boramsangjo/server/blob/develop/README.md#appgetuserinfo)
- [x] 푸시메시지 설정
  - ~~[ ] [app/setDeviceToken](https://github.com/sicamp17-boramsangjo/server/blob/develop/README.md#appsetdevicetoken)~~
    - `app/updateUserInfo` 기능에 포함시킴
- [ ] 유언 받을 사람 관리
  - [ ] [app/addReceiver](https://github.com/sicamp17-boramsangjo/server/blob/develop/README.md#appaddreceiver)
  - [ ] [app/removeReceiver](https://github.com/sicamp17-boramsangjo/server/blob/develop/README.md#appremovereceiver)
  - [ ] [app/getReceivers](https://github.com/sicamp17-boramsangjo/server/blob/develop/README.md#appgetreceivers)
- [x] 질문 추가/조회
  - [x] [app/addQuestion](https://github.com/sicamp17-boramsangjo/server/tree/master#appaddquestion)
  - [x] [app/getQuestion](https://github.com/sicamp17-boramsangjo/server/tree/master#appgetquestion)
- [ ] 유언 생성삭제
  - [x] [app/getTodaysQuestion](https://github.com/sicamp17-boramsangjo/server/blob/develop/README.md#appgettodaysquestion)
  - [x] [app/uploadImage](https://github.com/sicamp17-boramsangjo/server/blob/develop/README.md#appuploadimage)
  - [x] [app/uploadVideo](https://github.com/sicamp17-boramsangjo/server/blob/develop/README.md#appuploadvideo)
  - [x] [app/createAnswer](https://github.com/sicamp17-boramsangjo/server/blob/develop/README.md#appcreateanswer)
  - [ ] [app/deleteAnswer](https://github.com/sicamp17-boramsangjo/server/blob/develop/README.md#appdeleteanswer)
- [x] 유언 조회
  - [x] [getWillItem](https://github.com/sicamp17-boramsangjo/server#getwillitem)
  - [x] [getWIllItems](https://github.com/sicamp17-boramsangjo/server/blob/develop/README.md#getwillitems)
    - ~~일단 팬딩, [getUserInfo](https://github.com/sicamp17-boramsangjo/server/blob/master/README.md#appgetuserinfo)로 대체 가능함.~~ 앱단 캐싱 댑스가 너무 깊어짐. 이런 종류의 기능은 서버에서 지원하는 방향으로 진행함.
- [x] 사후에 다른 사람이 유언 읽기
  - [x] [getSessionTokenForReadOnly](https://github.com/sicamp17-boramsangjo/server/blob/master/README.md#appgetsessiontokenforreadonly)

cc. @t1t1 @kyungtaek

**Comment by lancifollia** [comment]
2017.02.21 변경사항
- 푸시메시지 app/setDeviceToken 삭제
  - app/updateUserInfo 에 기능을 포함시키기로 함.
- SessionToken은 일단 몽고DB의 ObjectID를 쓰는 걸로 함.

**Comment by lancifollia** [comment]
@kyungtaek willitemID는 questionID와 동일하게 가져가져 될 것 같습니다.
어차피 해당 유저 안에서만 unique하면 되는 값이니까 상관 없을 것 같아요.

**Comment by kyungtaek** [comment]
@lancifollia 넵 ㅎㅎ willItemID는 그럼 QuestionID랑 동일하게 가는 걸로 하시죠 :) 
그리고 초대코드 말인데요. 말씀하신 방법이 좀 더 맞는 것 같긴 해요. 
```
{
inviteCode:string, // random 생성
userID: ObjectID   // user의 _id값
}
```

이렇게 추가하고 getSessionForReadOnly에서 inviteCode와 birthday를 받아서 처리하면 될 것 같긴 한데요
아무래도 개발에 조금이라도 공수가 더 들어갈까봐 생각했던거구요 ㅎㅎ

편하신대로 구현하셔도 앱에서는 어쨋든 사망자의 WillItemList를 가져올 수 있는 키값만 얻을 수 있으면 상관없을 것 같습니다.

제가 괜히 sessionToken이라는 개념을 넣어서 일이 혼란스러워지는 것 같네요 ㅠ_ㅠ

**Comment by lancifollia** [comment]
@kyungtaek cc. @t1t1 
willitemID랑 questionID랑 다르게 하는게 좋을것 같네요. 같은 방식으로 하려고 했는데 비효율적인 것 같아요.
아무튼, 관련 내용 정리되면 적어놓을게요~

**Comment by lancifollia** [comment]
@kyungtaek cc. @t1t1 @weve6866 
[createAnswer](https://github.com/sicamp17-boramsangjo/server/blob/master/README.md#appcreateanswer), [getWillItem](https://github.com/sicamp17-boramsangjo/server/blob/master/README.md#getwllitem) 추가 되었습니다.

getWillItems 는 [getUserInfo](https://github.com/sicamp17-boramsangjo/server/blob/master/README.md#appgetuserinfo) 리턴 값에서 `willitems` 필드를 사용하는 것으로 대체가 가능한데요. 따로 추가가 필요하면 말씀해주세요~

**Comment by lancifollia** [comment]
@kyungtaek @weve6866 cc. @t1t1 
`deleteUser()`, `logout()` 에 의해 삭제되거나 로그아웃된 유저는 유저의 `status` 필드 값을 각각 `deleted`, `logout` 으로 설정하도록 할 예정입니다. (실제로 레코드를 삭제하진 않습니다.)
참고하세요~

**Comment by t1t1** [comment]
@kyungtaek @weve6866 cc. @lancifollia 
checkAlreadyJoin() 에서 등록된 번호의 경우 'status': 200, 'result': false 로 응답해도 될까요?

**Comment by lancifollia** [comment]
@t1t1 혁흔님, logout 도 추가 부탁드립니다~
동작은,
1. 로그아웃했을 때는 `user.status = 'logout'`, `user.deviceToken=''` 으로 바꾼다.
2. find_user() 에서도 logout 유저는 None 리턴
  - https://github.com/sicamp17-boramsangjo/server/commit/c205bf19fc4ecb854de66e133a220231260d9cf5#diff-87ab073469a8a4c2e8a35dbc1fd636b8R87 여기서 그냥 `status != normal` 이면 다 None 리턴하면 될 것 같아요.
3. login() 했을 때는 `'status' = 'normal'`로 status 업데이트해주는 로직 추가

**Comment by t1t1** [comment]
@lancifollia 
반영했습니다. 확인 부탁드리겠습니다. #8

**Comment by lancifollia** [comment]
@kyungtaek cc. @t1t1 
요청주신 내용 반영되었습니다.
- `getTodaysQuestion`: question에 대한 willitem이 존재할 경우 같이 내려줌
- `_id` 제거: 각각 `questionID`, `willitemID`, `userID`, `answerID`
- unique answerID

**Comment by lancifollia** [comment]
@kyungtaek cc. @t1t1 
`getSessionTokenForReadOnly()` 추가되었습니다. 이거 입력값에 `birthDay`는 string 포맷으로 적어주셨는데, 정확하게 어떤 포맷이면 좋을까요? 예시로 하나 알려주시면 반영해놓을게요. 아니면 createUser 할 때 처럼 timestamp로 넣는 것도 괜찮습니다.

**Comment by t1t1** [comment]
@lancifollia
birthDay 타입을 String 6자리로 변경요청 하셨습니다. (메모)
